name: Without Cache
on:
  workflow_dispatch:
  
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
 
    - name: Setup Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.7
        
    - name: Install requirements
      run: |
        pip install -r dev-requirements.txt
