name: PR
on:
  workflow_dispatch:
  
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Setup Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.7

    - uses: actions/cache@v4.0.2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
        
    - name: Install requirements
      run: |
        pip install --upgrade --upgrade-strategy eager -r dev-requirements.txt -e .
